version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/srv/app
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://root:root@127.0.0.1:3306/symf6-app?serverVersion=mariadb-10.8.3&charset=utf8mb4"
  

    depends_on:
      - mysql

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/srv/app:ro
      - ./configuration/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  mysql:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  db_data:
